### ISSUE TITLE
Stache: Helper - stache not providing temporary element for element callback

### ISSUE THREAD

**Issue by BigAB** [bitovi/canjs#1559] opened 2015-03-26 21:43 UTC
In a stache template helper, using the [element callback helper](http://localhost:8080/docs/can.stache.helper.html#section_Returninganelementcallbackfunction), the temporary element is not provided to the callback, but instead an empty string is provided:

#### With Mustache

http://jsfiddle.net/pt5cps21/2/
![This Works!](https://img.shields.io/badge/This-Works!-green.svg)

```javascript
var rndr = can.mustache("<ul>{{items}}</ul>");

can.mustache.registerHelper("items", function(options){
  return function(li){
    console.log(li);
    li.innerHTML = "I am an item";
    return li;
  };
});

var frag = rndr();

document.querySelector('body').appendChild(frag);
```
**output:**
```
* I am an item
```
The temporary element (an `li` in this case) is created and passed as first argument to the callback.

#### With Stache

http://jsfiddle.net/pt5cps21/3/
![This doesn't](https://img.shields.io/badge/This-Doesn't!-red.svg)

```javascript
var rndr = can.stache("<ul>{{items}}</ul>");

can.stache.registerHelper("items", function(options){
  return function(li){
    console.log(li);
    li.innerHTML = "I am an item";
    return li;
  };
});

var frag = rndr();

document.querySelector('body').appendChild(frag);
```

**output:**
```

```
The first argument ends up being an empty string. (and therefore not working)

**Comment by justinbmeyer** [comment] 2015-03-31 23:47
I just checked this, it does provide a textnode element.  Put a debugger in your fiddle and you'll see it's a text node.

This is not a bug.  Closing.

**Closed by justinbmeyer** 2015-03-31 23:47 UTC
Labels: Bug

**Comment by BigAB** [comment] 2015-03-31 23:50
The Documentation says it should (and Mustache does) return a <span></span> as the default element

**Comment by daffl** [comment] 2015-04-01 00:21
And other matching elements (e.g. a `<li>` when you are in a `<ul>`)

**Comment by justinbmeyer** [comment] 2015-04-01 01:04
This is not how stache works.  If the docs for stache says this, they are wrong.  Can you point to that in stache's docs?  I can update them.

Stache should not work this way ... it would undermine a big part of its performance benefits.

**Comment by justinbmeyer** [comment] 2015-04-01 01:08
If you need this, you can always swap in the element you need.

```
function(){
  return function(textNode){
    var tagName = can.view.elements.tagMap[ textNode.parentNode.nodeName ] || "span"
    var el = document.createElement(tagName);
    $(textNode).replaceWith(el)
  }
}
```

**Comment by BigAB** [comment] 2015-04-01 02:27
Looks like the original link was linked to localhost, I've edited it.
http://canjs.com/docs/can.stache.helper.html#section_Returninganelementcallbackfunction

So I'll just add this as a documentation error then.
