### ISSUE TITLE
Memory leak in CanJS template/model

### ISSUE THREAD

**Issue by jondubois** [bitovi/canjs#1393] opened 2015-01-06 05:24 UTC
When passing observables obtained from can.Model.findAll() or can.Model.find() into a can.view.mustache template generator, it appears to leak memory. The leak goes away when you call myobservable.attr() instead of passing the myobservable object directly to the template generator function. It doesn't matter whether the data comes from a real AJAX call or is provided by a fixture.

Here is a simple test to reproduce the issue (one button causes memory to leak, and the other doesn't - It just rerenders a template many times):

Note that you need to replace the all dependencies with their appropriate paths on your system.
To check memory consumption in Chrome, use the profiles tab of the developer console and take a memory snapshot before and after each test.

```html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>CanJS View Memory Leak Test</title>

    <script type="text/javascript" src='../../steal/steal.js'></script>
    <script type="text/javascript">
        steal(
            'jquery',
            'can/util',
            'can/view/mustache',
            'can/model',
            'can/util/fixture',

            function($, can) {

                can.fixture("/api/student/", function() {
                    return [
                        {
                            id: 0,
                            name: 'John Smith',
                            age: 15,
                            classGroup: '7A'
                        },
                        {
                            id: 1,
                            name: 'Alice Brown',
                            age: 14,
                            classGroup: '6B'
                        },
                        {
                            id: 2,
                            name: 'Bob Green',
                            age: 15,
                            classGroup: '7A'
                        },
                        {
                            id: 3,
                            name: 'Tim Tam',
                            age: 16,
                            classGroup: '7B'
                        }
                    ];
                });

                can.Model.extend('Models.Student',
                    /** @static */
                    {
                        create: 'NotImplemented_RESTAPI',
                        destroy: 'NotImplemented_RESTAPI',
                        findOne: 'NotImplemented_RESTAPI',
                        findAll: '/api/student/',
                        update: 'NotImplemented_RESTAPI',
                        attributes: {
                            id: 'number',
                            name: 'string',
                            age: 'number',
                            classGroup: 'string'
                        }

                    },
                    /** @prototype */
                    {});

                var mainTemplate = can.view.mustache(
                    '<input class="start-test-with-leak-button" type="button" value="Start test (with leak)" /> <input class="start-test-without-leak-button" type="button" value="Start test (without leak)" /><div class="main-area"></div>'
                );

                $(document.body).append(mainTemplate());

                var mainArea = $('.main-area');
                var startTestWithLeakButton = $('.start-test-with-leak-button');
                var startTestWithoutLeakButton = $('.start-test-without-leak-button');

                var withLeak = true;

                var addViewToDOM = function() {
                    mainArea.empty();

                    var studentsTemplate = can.view.mustache(
                        '<div>{{#each students}}Syllabus ID: {{id}}, name: {{name}}, age: {{age}}, class group: {{classGroup}}<br />{{/each}}</div>'
                    );

                    var studentsDef = Models.Student.findAll();
                    
                    studentsDef.done(function(students) {
                        var output;

                        if (withLeak) {
                            output = studentsTemplate({
                                students: students
                            });
                        } else {
                            output = studentsTemplate({
                                students: students.attr()
                            });
                        }

                        mainArea.append(output);
                    });
                };

                var startTest = function() {
                    console.log('STARTED TEST');

                    addViewToDOM();
                    var addViewInterval = setInterval(addViewToDOM, 500);
                    setTimeout(function() {
                        clearInterval(addViewInterval);
                        console.log('FINISHED TEST');
                    }, 10000);
                };

                startTestWithLeakButton.on('click', function() {
                    withLeak = true;
                    startTest();
                });

                startTestWithoutLeakButton.on('click', function() {
                    withLeak = false;
                    startTest();
                });
            }
        );
    </script>
</head>
<body>

</body>
</html>
```

**Comment by justinbmeyer** [comment] 2015-01-08 19:02
Thanks for posting this.

> Here is a simple test to reproduce the issue

Can you simplify it a bit more?  It's probably possible to create this situation without can.Model or can.fixture.  

I'm asking because I can't follow the code immediately.  I would have to setup this test, which would take some time, and really dive in.

If I can follow the code, it's possible I can immediately spot the problem and advise on a fix.  

Thanks!

**Comment by justinbmeyer** [comment] 2015-01-08 19:06
Also, how exactly do you know this is creating a leak.  When you say "It just rerenders a template many times", it appears that you keep adding more and more content to the page:

```
mainArea.append(output);
```

If this content is never removed, the amount of memory consumed will constantly go up.  

Are you sure you are seeing a leak?  Instead, I think you are just seeing that live-binding templates consume much more memory than flat DOM.  This is expected.

However, if you were to remove those elements from the page (with jQuery's $.fn.remove), you should notice memory going back to normal.

**Comment by justinbmeyer** [comment] 2015-01-08 19:16
Assuming I'm correct, and you'd like to reduce the memory consumed by live binding, please close this issue and create another titled: "Reduce live-binding memory consumption" that references your example (or post a new example without can.Model).  Thanks!

**Comment by justinbmeyer** [comment] 2015-01-08 19:17
Ah, I missed the "empty" of the main area.  Deleting my previous comments.

**Comment by justinbmeyer** [comment] 2015-01-08 19:18
Does this happen with mustache?

**Comment by Tarabyte** [comment] 2015-01-09 01:16
I've set up a fiddle. Not sure it is confirming the issue. http://jsfiddle.net/tarabyte/8g0qv4xj/
Well, the memory consumption is growing both cases. But not as if it was leaking something having model instances in closure.

**Comment by jondubois** [comment] 2015-01-09 03:55
@justinbmeyer Note sure, I haven't tried with stache yet.

@Tarabyte On my machine, the script I provided only leaks when you click on the 'Start test (with leak)' button.
In the slightly modified version to provided in JSFiddle, both leak. The first one leaks almost 3MB and the second one only leaks slightly over 1MB - So one is leaking more than the other... Could this be related to fiddler itself? Not sure why it's different.

When checking for memory leaks, I tend to check in complete isolation in a fresh tab - I'm not sure how fiddler interacts with all this code - It might skew results... I also noticed that fiddler runs the code in an iframe which can affect things too.

**Comment by jondubois** [comment] 2015-01-13 23:54
@justinbmeyer I will try to reproduce it using a simple Observe instead of the Model + Fixture combination - It might still leak. 

Ultimately, something appears to be holding on to references of the data. When I was debugging a while ago, I think I saw something about a _cache property somewhere in 'can' and I remember thinking that this could be the cause... Does that ring a bell?

**Comment by justinbmeyer** [comment] 2015-01-13 23:56
Yes, the model layer keeps instances, but only while they are bound. Clearing the page should clean them up.

**Comment by justinbmeyer** [comment] 2015-02-11 22:00
@jondubois I'm going to look into this Friday.  Anyway we can chat about it sometime on Friday?

**Comment by justinbmeyer** [comment] 2015-02-13 21:28
@jondubois I can confirm there is a leak in Mustache, but not in stache.

**Comment by jondubois** [comment] 2015-02-15 23:30
@justinbmeyer Thanks for looking into this. We will try to migrate our templates to stache.

**Closed** 2015-03-04 21:22 UTC
Labels: Bug

**Comment by dylanrtt** [comment] 2015-03-20 16:27
I am not sure that this has been fixed. The following line of code causes a memory leak:

    can.mustache('{{ test }}')(new can.Map())

The leak does not occur if the template is passed a plain object or when the template contains no mustache code. More complex examples such as using an actual template instead of a string also have the same problem.
