### ISSUE TITLE
can.compute nested key behaviour inconsistency with map bindings

### ISSUE THREAD

**Issue by stevenvachon** [bitovi/canjs#1231] opened 2014-09-15 20:05 UTC
`can.compute`s with `attr("value.nested")` do not behave the same as `attr("value").attr("nested")` in a map binding.

http://jsfiddle.net/prometh/La806u2d/

**Comment by chasenlehara** [comment] 2015-05-14 18:25
+1, we ran into [an issue caused by this bug in Sam’s](https://github.com/bitovi/samsclub/issues/4218).

**Comment by justinbmeyer** [comment] 2015-05-14 21:01
Closed by #1696.

**Closed by justinbmeyer** 2015-05-14 21:01 UTC
Labels: Bug
