### ISSUE TITLE
Compute memory leak with nested properties

### ISSUE THREAD

**Issue by dylanrtt** [bitovi/canjs#1676] opened 2015-05-07 18:57 UTC
Apparently if you manually add a compute to a Map, and the compute depends on a deep property of that same Map, it can leak bindings if used in conjunction with other event bindings in a certain order.

http://jsbin.com/nadelesulu/1/edit?html,js,console

**Comment by justinbmeyer** [comment] 2015-05-13 23:53
This is likely due to can.Map thinking that compute represents a define.get.

**Comment by justinbmeyer** [comment] 2015-05-14 18:44
Looked into this.  First, I don't think you should be writing your code like this.  There's no reason to bind to "change" events on `can.Map` anymore and you could use the define plugin to describe `petInfo`.

I'm not sure why you would set a compute as a property value of an attribute either.


All that being said, it would still be nice to make this work.  The problem is that this code creates a "cycle" of binding that isn't being detected while unbinding.

**Comment by justinbmeyer** [comment] 2015-05-14 18:44
#1231 is probably related

**Comment by justinbmeyer** [comment] 2015-05-14 21:01
Closed by #1696.

**Closed by justinbmeyer** 2015-05-14 21:01 UTC
Labels: Bug
