### ISSUE TITLE
can.Component events registered twice in 2.2.x

### ISSUE THREAD

**Issue by gsmeets** [bitovi/canjs#1778] opened 2015-07-11 22:19 UTC
I've made a fiddle using the code below. I'm using a custom processor here, just to be able to hook into the click handler. In my private setting I've tested it by adding a log message to the basic processor in can.control.

If you run the fiddle you can see in the console that the click processor is called twice.
The event is not triggered twice, so it's relatively harmless, but there seems to be something superfluous going on. I wonder if this has any performance impact.

This problem was introduced in 2.2.0, 2.1.4 is working as expected.

http://jsfiddle.net/gsmeets/8xq899vc/3/

    can.Control.processors.click = function( el, ev, selector, methodName, control ) {
        console.log( arguments )
        return $.noop;
    };
    
    can.Component.extend({
        tag: "event-fired-twice",
        template: "<p>test2</p>" ,
    
        events: {
            "click" : function () { }
        }
    });
    
    var renderer = can.stache( "<event-fired-twice>test</event-fired-twice>" );
    $( "body" ).append( renderer());

**Comment by alexisabril** [comment] 2015-07-15 06:22
This is due to the fix provided for: https://github.com/bitovi/canjs/pull/1422

Specifically the re-binding on line: https://github.com/bitovi/canjs/blob/c3b340422e4b3584b44e9f6f9940331c6b1e6d94/component/component.js#L272

Unsure what the impact would be of having a conditional rebind vs just rebinding.

**Comment by justinbmeyer** [comment] 2015-07-28 05:04
I'm betting this is fixed by #1803.  cc @daffl

**Comment by alexisabril** [comment] 2015-07-28 07:16
Confirmed, this is fixed by #1803. PR: https://github.com/bitovi/canjs/pull/1809 added just for the test. Note: test passes in master, however it looks like there's some merging going on. Current PR is for minor.

**Comment by alexisabril** [comment] 2015-07-28 07:16
Closing as this is fixed in master, #1809 is open to track progress of the test.

**Closed by alexisabril** 2015-07-28 07:16 UTC
Labels: Bug
