### ISSUE TITLE
Make possible to use stache by default

### ISSUE THREAD

**Issue by whitecolor** [bitovi/canjs#1610] opened 2015-04-06 22:20 UTC
Make possible to use stache as default rendering engine.

**Comment by daffl** [comment] 2015-04-07 00:31
You should be able to change [can.view.ext](http://canjs.com/docs/can.view.ext.html) to `.stache`. Mustache is still be loaded because of a hard dependency on can.Component though. The reason why is discussed in #1326. We will change it for 3.0.

**Comment by matthewp** [comment] 2015-04-07 01:32
With steal you can map mustache to stache:

```js
map: {
  "can/view/mustache/mustache": " can/view/stache/stache"
}
```

**Comment by whitecolor** [comment] 2015-04-07 15:29
@matthewp I've added this config to may package.json and got the error
```
TypeError: Error loading "package.json!npm" at http://localhost:3000/package.json
Cannot read property 'system' of undefined {stack: (...), message: "Error loading "package.json!npm" at http://localhot-…e.json↵Cannot read property 'system' of undefined"}message: "Error loading "package.json!npm" at http://localhost:3000/package.json↵Cannot read property 'system' of undefined"
```

**Comment by matthewp** [comment] 2015-04-07 16:37
I just tried it and it works.  The issue is that can/component uses `can.view.mustache`. So you'll have to replace that with `can.stache`. Probably a better way is to map can/view/mustache/mustache to `@empty` and in then in your code set `can.view.mustache = can.stache` although you're on your own from here, I haven't tried this to confirm :)

**Comment by whitecolor** [comment] 2015-04-07 16:42
```
can.view.mustache = can.stache
```
have to be done for all modules it is not convient.

Currenlty I have to use my fork for this https://github.com/whitecolor/canjs/blob/master/can.js. I just don't like this.

**Comment by matthewp** [comment] 2015-04-07 16:46
Ideally can/view/mustache should return `can.mustache`, not `can`. If it did and `can/component` used that instead of `can.view.mustache` then a straight mapping would work.  I think we can't do that until 3.0 for backwards compatibility reasons.

**Comment by whitecolor** [comment] 2015-04-07 19:55
Why I can not not map it with new steal and package.json? (in old steal I jest mapeed, and fork was not needed)

**Comment by matthewp** [comment] 2015-04-07 19:57
You can map it. But Mapping it is not enough.  can/component expects a `can.view.mustache` and mapping doesn't fix that.

**Comment by whitecolor** [comment] 2015-04-07 20:40
@matthewp as I've mentioned I've previously mapped `can.js` main file, but I'm unable to do this with new steal.

**Comment by matthewp** [comment] 2015-04-07 21:38
Can you post an issue in steal?  You should be able to do this, please provide an example of how you are trying to do your mapping.

**Comment by justinbmeyer** [comment] 2015-09-08 03:05
Closing.  Will re-open if a breaking example is provided.

**Closed by justinbmeyer** 2015-09-08 03:05 UTC

**Comment by whitecolor** [comment] 2015-09-08 13:15
I works but only with wrapper around can
```javascript
// can override for using stache as default engine
steal('can/util', 'can/control/route', 'can/model',
    'can/view/stache', 'can/component', function(can) {

        can.mustache = can.view.mustache = can.stache

        return can;
    });
```
