### ISSUE TITLE
Intermittent can.List corruption in iOS due to a bug in its JS optimizer

### ISSUE THREAD

**Issue by rjgotten** [bitovi/canjs#1787] opened 2015-07-15 12:44 UTC
There's a very obnoxious bug affecting iOS that can cause intermittent appearance of a bad `length` property on array-like objects:
https://bugs.webkit.org/show_bug.cgi?id=142792
http://trac.webkit.org/changeset/182058

It affects other frameworks like jQuery and underscore as well:
https://github.com/jquery/jquery/issues/2145
https://github.com/jashkenas/underscore/issues/2081

One of my team members has personally run afoul of this issue during `can.List` manipulations in a complex application where the code went hot enough to be treated by the JS optimizer in Safari. I can imagine others have as well, but have simply failed to identify the root cause.

When CanJS is running on top of jQuery a fully patched ( 1.11.3 or 2.1.4 ) version of jQuery is necessary to prevent problems from arising. Builds on top of other libraries are probably not so lucky.

This needs a patch to `can.each` and everything else that can iterate array-likes.

**Comment by justinbmeyer** [comment] 2015-07-15 14:26
I believe we have already made this fix.  @chasenlehara ?

**Comment by justinbmeyer** [comment] 2015-07-15 14:28
Duplicate of #1654

**Closed by justinbmeyer** 2015-07-15 14:28 UTC
