### ISSUE TITLE
can.Model: prevent bound models from being thrown out of the model store

### ISSUE THREAD

**Issue by boldakov** [bitovi/canjs#1524] opened 2015-03-16 16:39 UTC
If a can.Model instance is created via constructor, it is possible that it will drop out an existing model out of Model.store.

Suppose you create a model instance via constructor. This instance will be rendered later via popup widget. Another ajax call retrieves a list of models, one of which with the same *id*. This list is rendered and bound. When the popup is rendered, the instance from the list is thrown out of the Model.store and replaced with the constructed instance. As a result we have two rendered instances with the same *id* and live binding not working.

[The Fiddle with the issue] (http://jsfiddle.net/alexboldakov/2pf2d2mf/14/)

It seems that creating can.Model instances with defined *id* via constructor is not a good idea at all, because there is no chance that it will be merged with existing bound instance stored in Model.store. May be it is worth to explain in documentation. It is not clear how to do it the right way: use *can.Fixture* or something like *Todo.models([json])[0]*.

**Comment by justinbmeyer** [comment] 2015-03-16 18:53
`Todo.model(json)`

This is a duplicate of: #721

Closing

**Closed by justinbmeyer** 2015-03-16 18:53 UTC
