### ISSUE TITLE
Proposal: Argument support for `can-click`

### ISSUE THREAD

**Issue by zkat** [bitovi/canjs#1361] opened 2014-12-08 18:12 UTC
## Proposal

`can-click` handlers should support inline argument passing, right in the template. 

## Justification and Notes

This would obviate the need to entire categories of javascript-side viewmodel methods and allow us to add a ton of simple functionality right in the template. A common pattern in component-heavy application is writing relatively trivial methods that end up being thin wrappers over, say, `.attr()`.

I've also seen a common case where we have a loop, and then we do something like `<li can-click="{activateTab}" data-tab-name="@index">`, and then end up writing some JS that has to manually yank `tab-name` out of the element, and just do that dance a lot. We can do better just by allowing argument-passing.

## Example

Assuming #1360 is in place, the following would be a simple `tabs` component (collecting tabs array is left as an exercise to the reader, and might be potentially served by #500):

```html
<ul class="tabs">
  {{#each tabs}}
    <li can-click="{self.attr 'tabIndex' @index}">
      {{name}}
    </li>
  {{/each}}
</ul>
{{#each tabs}}
  {{#equal self.tabIndex @index}}
    {{{content}}} {{! or <content select="nth(@index)"></content> }}
  {{/each}}
{{/each}}
```

**Comment by justinbmeyer** [comment] 2015-02-11 22:25
This is a duplicate of #1219.  Can't agree more. But closing as that issue was first and includes ideas on how to pass the element and events objects.

**Closed by justinbmeyer** 2015-02-11 22:25 UTC
Labels: Feature Request, Future Feature
