### ISSUE TITLE
can-value throws exception when inside an empty scope

### ISSUE THREAD

**Issue by whitecolor** [bitovi/canjs#1052] opened 2014-06-05 06:23 UTC
http://jsfiddle.net/xKc3H/380/

```javascript
can.Component({

    tag: 'my-comp',
    
    scope: {
        text: 'Some text',
        canValue: false //if canValue is false/empty there is an error
    },        
    
    template: '<input {{#canValue}}can-value="text"{{/canValue}}/>'

})

$('body').append(can.view.mustache('<my-comp/>')())
```

**Comment by alexisabril** [comment] 2015-10-02 02:54
@whitecolor Could you verify this is still an issue? That fiddle doesn't show an error currently, tested with v2.0.0, 2.1.0 & 2.2.9

**Comment by daffl** [comment] 2015-10-22 16:47
I couldn't reproduce as well. Closing this issue, please reopen if it still persists in minor.

**Closed by daffl** 2015-10-22 16:47 UTC
