### ISSUE TITLE
Can component with malformed HTML in template causes Chrome to spin indefinitely

### ISSUE THREAD

**Issue by kylegifford** [bitovi/canjs#1472] opened 2015-02-25 23:15 UTC
For code like this, where the closing bracket is missing from the input, resulting in malformed HTML, Chrome fails to load the page and then spins indefinitely, crashing the browser. This should throw a warning about malformed HTML and exit.

```javascript
can.Component.extend({
	tag: 'todos-create',
	template: can.stache('<input id="new-todo"'),
});
```

**Comment by daffl** [comment] 2015-02-26 21:24
I put your example into [a Fiddle](http://jsfiddle.net/5Ljymras/) and get a

> Uncaught Parse Error: <input id="new-todo"

in the console. Is the issue you are observing reproducable in a Fiddle (fork from [here](http://jsfiddle.net/donejs/qYdwR/))?

**Comment by daffl** [comment] 2015-07-24 15:39
Closing this one since I can't reproduce. We can reopen if we find a breaking Fiddle.

**Closed by daffl** 2015-07-24 15:39 UTC
Labels: Bug
