### ISSUE TITLE
Mustache: Attribute values are fixed after can.Deferred resolves (against live binding and future rendering)

### ISSUE THREAD

**Issue by bmomberger-reciprocity** [bitovi/canjs#326] opened 2013-03-20 23:07 UTC
http://jsfiddle.net/air_hadoken/zjauS/3/

Repro steps:
1. Create a Can Mustache, rendered with an Observe that contains a Deferred
2. Change an attribute in the Deferred, or the Deferred itself.
Result: bound values in the Mustache do not change.
3. Render a new Mustache instance with the same Observe, post-attribute change.
Result: Mustache is rendered with originally resolved values, not the updated values.

Expected would be that these values can be changed after their original setting.  The spec for jQuery Deferred states that once a Deferred is resolved, it can't be re-resolved to another value, and any done() handlers will receive the first resolved value, so it seems incompatible with wanting to update live-bound views later.

What I notice is that after the Deferred is applied to an Observe property, calling .attr() as a setter sets the "text" property of the Deferred object so later .attr() accessors will return the new value.  These are the possibly more compatible approaches I've been brainstorming: 
(1)  replace the Deferred with an Observe of the Deferred's resolved value the first time attributes are set; 
(2) on attribute change, pipe the Deferred to another Deferred that resolves to the updated attributes, and replace the original Deferred with the piped one; 
(3) use progress() and notify() instead of resolve/done to trigger rendering the view; for AJAXen, this would have to wrap the original can.ajax.
(4) have can.view() always implement Promise, and resolve to a render function if the data parameter is undefined.  This way I can add it to a $.when with my AJAX calls, and render it without putting Deferreds into my Observe.

Would love to hear what the CanJS team thinks of this.

**Comment by justinbmeyer** [comment] 2015-02-11 18:28
@bmomberger-reciprocity This seems like a duplicate of #179 - Making Deferreds Observable.  Please comment and I'll re-open if I'm wrong about that.  Thanks!

**Closed by justinbmeyer** 2015-02-11 18:28 UTC
Labels: can.Mustache
